### ISSUE TITLE
label

### ISSUE THREAD

**Issue by saisumanthkumar** [mrinal41298/gitsetgo#116]
@garimasingh128 as per OSS PORT Instructions only Merged PR's with `hacktoberfest-accepted` label is approved.

Current label is `Hacktoberfest-accepted` please update the first letter ,It'll be very helpful 
Thank you!!!

**Comment by garimasingh128** [comment]
This repository has hacktoberfest label. It shouldn't be an issue.

**Comment by saisumanthkumar** [comment]
@garimasingh128 yeah but It is ok with hacktoberfest, But from OSS port they said it should be only `hacktoberfest-accepted` to count towards ossport contributors
<br>
![Screenshot (197)](https://user-images.githubusercontent.com/74057515/138303327-c813a41b-20a5-486b-99af-4897102a9564.png)
